### ISSUE TITLE
PM Description: Exception in server tick loop  java.lang.IllegalArgumentException: Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by reddvilzz** [Corosauce/ZombieAwareness#15]
http://pastebin.com/4dbk05mr

I keep getting this crash, it happens randomly I guess. What seems causing it?
Edit: I think I found the issue, the issue come from Special Mobs Mod.
What I did is using peaceful mode and then just run around and play for a while until it crashes with the same crash log.

After crash I logged back in and noticed there is a mob that is spawned from Special Mobs Mod, at this time it is the Fishing Baby Zombie. I think Zombie Awareness tried to put the effect on to the Special Mobs Mod? Which is why it crashing? I still don't know how to workaround it though.

Thank you.

**Comment by reddvilzz** [comment]
Okay found a workaround for this. I just disable ZA buffs on zombies when spawned seems fixed it frim crashing.

Downside is the zombies won't have any special potion buffs on them.

**Comment by Corosauce** [comment]
Hrrmm, the fix I applied in 1.10.2 must not have gotten backported, I'd recommend keeping the random speed boost off yeah, it could also cause some speed boosts that are way too fast, if I recal correctly it was due to baby zombies using the same ID for the boost, and by default zombie awareness disables baby zombies, special mobs probably used those in some way.

**Comment by reddvilzz** [comment]
Okay thank you for clarifying. I guess I can close the issue now.
