### ISSUE TITLE
[1.7.10, possibly more recent versions also] Mobs Ignore Invisibility

### ISSUE THREAD

**Issue by DarianLStephens** [Corosauce/ZombieAwareness#22]
Yes, I know that's a vanilla issue as well. The problem is that even when a mod (Like PotionCore) fixes invisibility, this mod makes mobs pathfind towards you. Even though they don't attack immediately, they try to pathfind to the same block you're on, which means if you aren't quite quick enough, they'll catch up and bump into you, alerting them to your presence, and causing them to attack you.
Is there at least a way to disable that pathfinding, leaving the mod to just handle sound and scent tracking, while everything else stays as-is?

**Comment by Corosauce** [comment]
Looks like at some point (probably after 1.7.10 version) I made sure the extra targetting feature ignores creative and invisible players, so they shouldn't actually target attack you unless another mod does that. You can potentially still create sound or smell senses that will make them wander closer, which I'll leave in for invisible players as intended design unless decided otherwise.

**Comment by DarianLStephens** [comment]
I agree that invisible players creating sounds and smells would make it much more interesting.
Would it be possible to have a 1.7.10 update to make the main pathfinding ignore invisible players, too?
