### ISSUE TITLE
New build also crash in the edncity. And a  suggestion.

### ISSUE THREAD

**Issue by blood789** [Corosauce/ZombieAwareness#62]
I think its the same as https://github.com/Corosauce/ZombieAwareness/issues/59

I've linked a new build that should fix this there.

_Originally posted by @Corosauce in https://github.com/Corosauce/ZombieAwareness/issues/61#issuecomment-1008492203_

-------------------------
In the new version, the game will still crash if entering an end city. 
Only I change the awareness_Sound = false, it do not crash again. 

So, I have a suggestion, are you giving each dimension a separate config file?

For example, in different dimensions, monsters have different perception and tracking ranges.

**Comment by lamoyrl90** [comment]
I can confirm this. I posted a reply in #59

**Comment by Corosauce** [comment]
Thanks for the fast testing

Mkay, turned the performance tweaking up to 11, try this one out https://www.curseforge.com/minecraft/mc-mods/zombie-awareness/files/3601776

Performance update:
- Reduce how far a sound sense can spawn from player for explosions, noisy zombies, pistons for performance reasons
- Reworked order of code to prevent potentially trying to spawn senses during chunk generation (should address item frames trying to play sounds as they generate in end cities)
- Make sure mobs only pathfind once every 15 seconds to maximize performance without much feature loss (configurable via tickCooldownBetweenPathfinds)
- Optimize code performance relating to sound sense source spawning

Feature Update:
- Tweak light sensing feature to have mobs stay closer, be a bit more aggressive
- Tweak noisy zombies feature, will more aggressively attract other mobs when they are close to you (configurable via noisyZombiesReinforceOddsTo1)
- Random slightly speed boosted zombies feature working again, also made it randomly slow down baby zombies


Unless the end city is generating right beside you within 4 blocks theres no way it should be freezing up now, unless something else is to blame and in that case I'll need fresh crash reports.

If issues persist even with this version, and you aren't having the problem in the overworld, you can set awareness_Sound_OverworldOnly to True in Features.toml instead of outright turning sound senses off via the other config, should be a good comprimise

**Comment by lamoyrl90** [comment]
The game's no longer freezing up when generating large structures with sound senses turned on. I'll post again if I encounter the issue again, but it looks good so far!

**Comment by Corosauce** [comment]
:partying_face:
