### ISSUE TITLE
ZA Conflict with Vamprism during village generation. Minecraft 1.16.5

### ISSUE THREAD

**Issue by VoidOloth** [Corosauce/ZombieAwareness#74]
In approaching 3 villages across 3 seeds server would crash while approaching the villages. Upon removing ZA approaching the villages no longer caused crashes. Examining the villages showed that there was the Vampire hunter trainer and his house in every village that was causing a crash and, The Vampire Hunter trainer and his house were not in any of the other villages which did not cause problems. Hopefully this might help you track down the issue and if possible fix it. If you would like can also include map seeds used and locations of the village. 

[crash-2022-03-06_03.46.46-server.txt](https://github.com/Corosauce/ZombieAwareness/files/8192968/crash-2022-03-06_03.46.46-server.txt)

**Comment by TelepathicGrunt** [comment]
Issue is caused by item frames being spawned by any structure. This includes better strongholds, vampirism, etc. Any structures.  The Item Frame is setting the item which plays a sound automatically (and this is during worldgen it seems). Zombie awareness hooks up to that play sound and tries to call get blockstate with the wrong world passed in (serverlevel I bet instead of the worldgenregion). Which makes that world wait until the chunk is finished generating. Except when that class is inside the generating chunk, the chunk is now waiting on itself to finish which is a deadlock and stalls the game forever.

Doesn't seem like this check is working
https://github.com/Corosauce/ZombieAwareness/blob/c502072c48345aa9d15011165f34d25b89dff07a/src/main/java/com/corosus/zombieawareness/ZAUtil.java#L619

**Comment by TelepathicGrunt** [comment]
workaround mod is uploaded that fixes this specific issue in 1.16.5: https://www.curseforge.com/minecraft/mc-mods/zombie-awareness-freeze-fix
