### ISSUE TITLE
Item Frames soft lock world at 100% loading (1.16.5)

### ISSUE THREAD

**Issue by UselessBullets** [Corosauce/ZombieAwareness#98]
Issue: When placing and item frame and inserting an item the game works fine until you save and then reload the world. The world loading will then get stuck at 100% forever and cpu usage drops to about ~1%. The issue occurred for me with a modpack containing just 
-forge 36.2.34
-CoroUtil-1.16.5-1.2.37
-zombieawareness-1.16.5-1.12

Reproduce:
Step 1: Create new world
Step 2: Place item frame with item
Step 3: Exit and Save world
Step 4: Attempt to load world

**Comment by TelepathicGrunt** [comment]
A workaround mod is uploaded that fixes this specific issue in 1.16.5. See if this help resolve the freezing/deadlock that you are having: https://www.curseforge.com/minecraft/mc-mods/zombie-awareness-freeze-fix

**Comment by Corosauce** [comment]
Wow great work. I remember at some point I confirmed a cascading chunkgen issue relating to Entity senses that resulted in the server thread freezing. At this point I have no idea what version that was, maybe 1.18.2. IIRC My fix was a range limit on how far from a player a sense can spawn. Don't see issue reports about it since this so I must have fixed it, If im extra bored I might backport that fix.
